[package]
name = "PikchrMirror"
version = "0.1.0"
edition = "2021"

[dependencies]
pikchr = "0.1.*"
resvg = "0.44.0"

[dependencies.floem]
git = "https://github.com/lapce/floem"
features = ["editor", "default-image-formats", "rfd-async-std"]