[package]
name = "PikchrMirror"
version = "0.1.3"
edition = "2021"

[dependencies]
log = "0.4.*"
pikchr = "0.1.*"
pretty_env_logger = "0.5.*"
xml-rs = "1.0.*"

[dependencies.resvg]
version = "0.45.*"

[dependencies.iced]
version = "0.13.*"
features = ["svg", "highlighter"]

[dependencies.iced_wgpu]
version = "0.13.*"

[profile.release]
opt-level = "s" # or "z"
codegen-units = 1
lto = "thin" #alternatives "fat" or "false"
strip = "debuginfo"
