name: Pikchr Unit Tests

on:
  push:
    branches-ignore:
      - master # uses the test on pull request
      - develop # uses the test on pull request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --release --all-features
